name: Deploy Apache with PHP on Staging Server
on:
  push:
    branches:
      - main
  workflow_dispatch: null

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Deploy to Staging Server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/
          remote_host: ${{ secrets.STAGING_SERVER_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}

      - name: Copy SSH Key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo ${{ secrets.SSH_PRIVATE_KEY }} | tr -d '\r' > /home/ubuntu/.ssh/id_rsa
            chmod 600 /home/ubuntu/.ssh/id_rsa

      - name: Install Apache and PHP
        if: always()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y apache2 php libapache2-mod-php
            sudo sed -i 's/Listen 80/Listen 3000/' /etc/apache2/ports.conf
            sudo sed -i 's/<VirtualHost *:80>/<VirtualHost *:3000>/' /etc/apache2/sites-available/000-default.conf
            sudo systemctl restart apache2 || (sudo systemctl status apache2 && exit 1)
            sudo ufw allow 3000 # Allow new port
            
      - name: Create PHP Info File
        if: always()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/info.php
            sudo chmod 644 /var/www/html/info.php
