name: Deploy LAMP Stack on Staging Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Deploy to Staging Server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/
          remote_host: ${{ secrets.STAGING_SERVER_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}

      - name: Deploy and Install Dependencies
        if: always()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y apache2 mariadb-server php php-mysql
            sudo systemctl start apache2
            sudo systemctl enable apache2
            sudo systemctl start mysql
            sudo systemctl enable mysql
            sudo mysql_secure_installation
            sudo ufw allow 'Apache'
            sudo ufw allow 'Apache Full'
            sudo systemctl restart apache2
